server:
  port: 8761
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  file: logs/application.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    com.cts.mc: INFO
  

      
  